### ISSUE TITLE
RollingUpdate is not working for small pod counts 

### ISSUE THREAD

**Issue by Vad1mo** [pomerium/pomerium-helm#107]
I the current setup with replication count of 1 RollingUpdate aren't working.

To solve the issue `maxUnavailable` should be set to `0` at least replica count `<3` see: https://stackoverflow.com/a/46377159/1156199

**Comment by travisgroth** [comment]
I don't think that's relevant in the current chart.  For better or worse, we're relying on the defaults for `rollingUpdate`:

```yaml
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
```

According to [the docs](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment) this should implicitly arrive at `maxUnavailable: 0` and `maxSurge: 1` for low replica counts.

Is there something in particular you're seeing?
