### ISSUE TITLE
Allow injecting specific environment variables into only the 'authenticate' Pods

### ISSUE THREAD

**Issue by davidrosson** [pomerium/pomerium-helm#121]
## Overview

I use environment variables passed via the existing `extraEnv` capability to set the identity provider (GitLab) credentials: `IDP_CLIENT_ID` and `IDP_CLIENT_SECRET`. The reason for using environment variables rather than `authenticate.idp.{clientID, clientSecret}` is that my credential values are stored in Vault, and are accessed by the Pods dynamically using the `bank-vaults` webhook mechanism:

```
extraEnv:
  IDP_CLIENT_ID: vault:ci/data/sandbox/pomerium#IDP_CLIENT_ID
  IDP_CLIENT_SECRET: vault:ci/data/sandbox/pomerium#IDP_CLIENT_SECRET
```

This functionality currently works fine. However, the only way to set environment variables in Pods is to use this "global" `extraEnv` capability, which injects the defined environment variables into _all_ components' Pods (`authenticate`, `authorize`, `cache`, `proxy`). Since the credentials are only needed by the `authenticate` Pods, it would be useful to be able to set these environment variables _only_ for those Pods that require them, e.g.:

```
authenticate:
  deployment:
    extraEnv:
      IDP_CLIENT_ID: vault:ci/data/sandbox/pomerium#IDP_CLIENT_ID
      IDP_CLIENT_SECRET: vault:ci/data/sandbox/pomerium#IDP_CLIENT_SECRET
``` 

Extending my use of environment variables for credential injection, it would be nice if the Helm deployment could generate an optional Kubernetes `ServiceAccount` to be used by the `authenticate` deployment (only if RBAC is enabled). This would allow scoping access to Vault secrets via a policy/auth configuration bound to the generated `ServiceAccount`.
