### ISSUE TITLE
'extraVolumes' value breaks Pomerium chart

### ISSUE THREAD

**Issue by denis-buravlev** [pomerium/pomerium-helm#123]
**Description:**
The chart provides an ability to define an additional volumes by `extraVolumes` parameter. But if you set the parameter then helm throws the following error:
`Error: YAML parse error on pomerium/templates/authenticate-deployment.yaml: error converting YAML to JSON: yaml: line 75: mapping values are not allowed in this context`

**Steps to reproduce:**
1. Create a file `test.yaml` with the following content:
```
extraVolumes:
    - name: foo
      configMap:
        name: bar
        optional: false
```

2. Execute command: `helm install --dry-run -f test.yaml pomerium charts/pomerium/`
