### ISSUE TITLE
Unable to change log_level for the proxy

### ISSUE THREAD

**Issue by Djiit** [pomerium/pomerium-helm#128]
Hey, I tried the following values : 

```yaml
config:
  proxy_log_level: info
```

```yaml
proxy:
  config:
    proxy_log_level: info 
```

With no luck. How can we set the proxy log level ?

Thanks for your help.

**Comment by Djiit** [comment]
Ho, this worked : 

```yaml
extraEnv:
  LOG_LEVEL: info
  PROXY_LOG_LEVEL: info
```

Should we add a note somewhere in the docs ? I can do a PR if you point me the right direction.
