### ISSUE TITLE
(feat): Do not set authorize tls host when forwardAuth is enabled

### ISSUE THREAD

**Issue by lukasmrtvy** [pomerium/pomerium-helm#129]
Authorize tls host ( https://github.com/pomerium/pomerium-helm/blob/master/charts/pomerium/templates/ingress.yaml#L19 ) in ingress should not be set when `forwardAuth.enabled=true`. 

```
spec:
  tls:
    - secretName: secret.pomerium.com
      hosts:
        - "authorize.pomerium.com" # ingress does not even contain authorize.pomerium.com host
        - "authenticate.pomerium.com"
```
Problem:
If You are using external-dns, it will create authorize CNAME record, which is pointless operation.
