### ISSUE TITLE
IDP scopes written in config as string instead of list

### ISSUE THREAD

**Issue by albertrdixon** [pomerium/pomerium-helm#149]
## What happened?

The operator was failing to start up due to being unable to read generated config file.

```
Error: failed to set base config from /etc/pomerium/config.yaml: failed to unmarshal configuration: yaml: unmarshal errors:
  line 10: cannot unmarshal !!str `openid,...` into []string
```

## What did you expect to happen?

The generated config file would be valid and the operator would start up cleanly

## Steps to reproduce

1. Set multiple IDP scopes in your values.yaml

      ```yaml
      authenticate:
        idp:
          scopes: "openid,offline_access,profile,email,groups"

2. Deploy / upgrade using this values file
3. The generated config will include an invalid idp_scopes and the operator will fail

## What's your environment like?

- Chart version:  `12.1.0`
- Container image: `v0.10.0`
- Kubernetes version: `v1.17.9`
- Cloud provider:  `aws`
- Other details: `IDP - OKTA`

## What are your chart values?

Only Posting the relevant `authenticate` section
```values.yaml
authenticate:
  existingTLSSecret: pomerium-authenticate-tls
  idp:
    provider: okta
    url: "https://***"
    scopes: "openid,offline_access,profile,email,groups"
```

## What are the contents of your config secret?

Showing `pomerium-base` as the operator did not render the main config
Only showing relevant section

```values.yaml
idp_provider: okta
idp_scopes: openid,offline_access,profile,email,groups
```

## What did you see in the logs?

Operator logs:
```logs
Error: failed to set base config from /etc/pomerium/config.yaml: failed to unmarshal configuration: yaml: unmarshal errors:
  line 10: cannot unmarshal !!str `openid,...` into []string
```
