### ISSUE TITLE
config.policy should support multi-line templates

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium-helm#153]
## What happened?

I defined the following in my values.yaml file:
```yaml
config:
  policy: |
      {{- range .Values.services }}
        - from: https://{{ .from }}
          to: {{ .to }}
      {{ toYaml .policy | indent 4 }}
      {{- end }}
```

`services` contains some home made structure to declare the various elements of the policy.

`pomerium.config.dynamic` is calling `{{ tpl (toYaml .Values.config.policy) . | indent 2 }}` and thus the resulting policy is:
```yaml
policy:
  |
  - from: https://xxxxx
    to: yyyyy
    etc…
```

As you can see, the `|` stayed because of the toYaml I believe.

## What did you expect to happen?

That the content of the `config.policy` is used directly as a template and as yaml.

I fixed the problem just by removing the `toYaml` operator in the `_helpers.tpl` file but I'm not sure it is not going to introduce regressions for other requirements :)

## What did you see in the logs?

Pomerium failed to parse the policy because it is expecting an array.
