### ISSUE TITLE
Pomerium POD_NAME instruction is not working

### ISSUE THREAD

**Issue by shinebayar-g** [pomerium/pomerium-helm#163]
## What happened?

After installing pomerium via helm chart, following instruction is not working.

```
NAME: pomerium
LAST DEPLOYED: Wed Oct 14 16:28:02 2020
NAMESPACE: pomerium
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Get the Pomerium URL by running:
  export POD_NAME=$(kubectl get pods -n pomerium -l "component=server,app=pomerium,release=pomerium" -o jsonpath="{.items[0].metadata.name}")
  echo http://127.0.0.1:8000/
  kubectl -n pomerium port-forward $POD_NAME 8000:8000
```

```
✗ export POD_NAME=$(kubectl get pods -n pomerium -l "component=server,app=pomerium,release=pomerium" -o jsonpath="{.items[0].metadata.name}")
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].metadata.name}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```

## What did you expect to happen?

Getting pomerium URL successfully.

## Steps to reproduce

1. install pomerium via helm chart
2. follow instructions. Specially following line isn't working.

```
export POD_NAME=$(kubectl get pods -n pomerium -l "component=server,app=pomerium,release=pomerium" -o jsonpath="{.items[0].metadata.name}")
```

## What's your environment like?

- Chart version: `12.5.0`
- Container image: 
- Kubernetes version: `Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider: AWS
- Other details:

## What are your chart values?

I've configured only following items.

```yaml
config:
  rootDomain: internal.mydomain.com
  sharedSecret: "RANDOM"
  cookieSecret: "RANDOM"

authenticate:
  idp:
    provider: github
    clientID: "REDACTED"
    clientSecret: "REDACTED"
    url: "https://authenticate.internal.mydomain.com"
    scopes: ""
    serviceAccount: "BASE64 value of json file with username, personal_access_token"
```

## What are the contents of your config secret?

`kubectl get secret pomerium -o=jsonpath="{.data['config\.yaml']}" | base64 -D`

```
✗ kubectl get secret pomerium -o=jsonpath="{.data['config\.yaml']}" | base64 -D
base64: invalid option -- 'D'
Try 'base64 --help' for more information.
```
