### ISSUE TITLE
pomerium-cache pod startup failing with redis: `invalid port ":%Adar5{&" after host`

### ISSUE THREAD

**Issue by stuartpb** [pomerium/pomerium-helm#167]
I've got `redis.enabled:true` in my Helm Release values, and my `pomerium-cache` pod is in CrashLoopBackOff:

```logs
[stuart@stushiba ~]$ kubectl logs pomerium-cache-56587db64-nln56 -n pomerium 
{"level":"info","version":"0.10.6-1601514118+a711475","time":"2020-10-21T05:18:59Z","message":"cmd/pomerium"}
{"level":"warn","time":"2020-10-21T05:18:59Z","message":"config: cache url will be deprecated in v0.11.0"}
{"level":"warn","Addr":":5443","GRPCAddr":":5443","time":"2020-10-21T05:18:59Z","message":"config: default http handler changed"}
2020/10/21 05:18:59 [INFO][cache:0xc000311f80] Started certificate maintenance routine
{"level":"info","port":"42531","time":"2020-10-21T05:18:59Z","message":"gRPC server started"}
{"level":"info","port":"36703","time":"2020-10-21T05:18:59Z","message":"HTTP server started"}
{"level":"warn","service":"directory","provider":"github","error":"unexpected end of JSON input","time":"2020-10-21T05:18:59Z","message":"invalid service account for github directory provider"}
{"level":"warn","provider":"github","time":"2020-10-21T05:18:59Z","message":"no directory provider implementation found, disabling support for groups"}
{"level":"warn","service":"databroker","error":"redis.DialURL(): parse \"rediss://:%Adar5{&?<>\\\"7ZDlSXMxSOFt\\\"!s4g?C\\\\@pomerium-redis-master.pomerium.svc.cluster.local:6379\": invalid port \":%Adar5{&\" after host","time":"2020-10-21T05:18:59Z","message":"failed to save server version."}
{"level":"info","time":"2020-10-21T05:18:59Z","message":"enabled cache service"}
{"level":"info","service":"identity_manager","time":"2020-10-21T05:18:59Z","message":"initializing directory groups"}
{"level":"info","addr":"127.0.0.1:42531","time":"2020-10-21T05:18:59Z","message":"starting control-plane gRPC server"}
{"level":"info","addr":"127.0.0.1:36703","time":"2020-10-21T05:18:59Z","message":"starting control-plane HTTP server"}
{"level":"info","service":"databroker","type":"type.googleapis.com/directory.Group","time":"2020-10-21T05:18:59Z","message":"get all"}
{"level":"fatal","error":"failed to initialize directory groups: error getting all directory groups: rpc error: code = Unknown desc = redis.DialURL(): parse \"rediss://:%Adar5{&?<>\\\"7ZDlSXMxSOFt\\\"!s4g?C\\\\@pomerium-redis-master.pomerium.svc.cluster.local:6379\": invalid port \":%Adar5{&\" after host","time":"2020-10-21T05:19:01Z","message":"cmd/pomerium"}
```

**Comment by stuartpb** [comment]
Here's my config.yaml:

```yaml
address: ":443"
grpc_address: ":443"
certificate_file: "/pomerium/cert.pem"
certificate_key_file: "/pomerium/privkey.pem"
certificate_authority_file: "/pomerium/ca.pem"
authenticate_service_url: https://authenticate.horn.horse
authorize_service_url: https://pomerium-authorize.pomerium.svc.cluster.local
cache_service_url: https://pomerium-cache.pomerium.svc.cluster.local
idp_provider: google
idp_scopes: 
idp_provider_url: 
forward_auth_url: https://pomerium-proxy.pomerium
cookie_secret: N3Zpe2NBXlxkamonSi1laSw7UEBxXmBocCNkZ3xidkU=
shared_secret: YypYSD8vdTEpa3F+Rl1ZNW4uNTdDc0x2OXEyYFtETFM=
idp_client_id: REPLACE_ME
idp_client_secret: REPLACE_ME
databroker_storage_type: redis
databroker_storage_connection_string: rediss://:%Adar5{&?<>"7ZDlSXMxSOFt"!s4g?C\@pomerium-redis-master.pomerium.svc.cluster.local:6379
databroker_storage_tls_skip_verify: false    
policy:
  - allowed_users:
    - github/stuartpb
    - s@stuartpb.com
    from: https://alertmanager.horn.horse
    to: http://kps-alertmanager.prometheus.svc.cluster.local:9093
  - allowed_users:
    - github/stuartpb
    - s@stuartpb.com
    from: https://prometheus.horn.horse
    to: http://kps-prometheus.prometheus.svc.cluster.local:9090
  - allowed_users:
    - github/stuartpb
    - s@stuartpb.com
    from: https://grafana.horn.horse
    pass_identity_headers: true
    to: http://kube-prometheus-stack-grafana.prometheus.svc.cluster.local
  - allowed_users:
    - github/stuartpb
    - s@stuartpb.com
    from: https://rook-ceph.horn.horse
    to: http://rook-ceph-mgr-dashboard.rook-ceph.svc.cluster.local:7000
  - allowed_users:
    - github/stuartpb
    - s@stuartpb.com
    from: https://kubernetes-dashboard.horn.horse
    tls_skip_verify: true
    to: https://kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local
```

It's especially weird because the output from `kubectl get secrets -n pomerium pomerium-redis-password -o jsonpath={.data.password} | base64 -d` isn't `%Adar5{&?<>"7ZDlSXMxSOFt"!s4g?C\`, but `ik7c:6yJVv1&)5A0kId-3|1nsI~yC=b*`.
