### ISSUE TITLE
Specify custom basic auth header as secret

### ISSUE THREAD

**Issue by robertgates55** [pomerium/pomerium-helm#175]
I'm using pomerium (installed via helm) to proxy access to an elasticsearch instance. I'm using `set_request_headers` to pass the basic auth token - the below works well. However, having a base64 encoded password directly in our config like this doesn't comply with our company security policies:
```
      policy:
      - from: https://kibana.with.auth.com
        to: http://kibana-kb-http.logging.svc.cluster.local:5601
        allowed_domains:
        - rob.com
        set_request_headers:
          Authorization: Basic blahblahblahblahblahblahblah
      - lots
      - of
      - others
```

Is there any way to provide that token/header as a kubernetes secret instead of directly in config?

I've tried `Authorization: Basic ${ELASTIC_TOKEN}` (and used extraEnvFrom to pass in as a secret) but it doesn't seem to resolve the env. I've also been looking at encoding the whole config and passing that in as a secret, but it makes adding new policies in the future a complete pain.

Any ideas on how I could do this? Or other ideas for setting this header?
