### ISSUE TITLE
help setting up behind alb

### ISSUE THREAD

**Issue by TC-robV** [pomerium/pomerium-helm#201]
i am currently using this for my values. 
```
config:
  rootDomain: example.xyz
  generateTLS: true
  insecure: false

  policy:
    - from: https://graphite-ha.example.xyz
      to: https://graphite-web
      allowed_domains:
        - example.xyz
      tls_skip_verify: true
      
ingress:
  authenticate:
    name: "int-auth"
  annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/subnets: subnet-xxxx, subnet-xxxxx
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:xxxxxx:certificate/xxxxx
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
  tls:
    hosts:
      - graphite-ha.example.xyz
  hosts:
    - graphite-ha.example.xyz
proxy:
  service:
    type: LoadBalancer

authenticate:
  idp:
    provider: "onelogin"
    clientID: "xxxxxxxxxx"
    clientSecret: "xxxxxxxxxx"
    url: "https://openid-connect.onelogin.com/oidc"
  service:
    type: LoadBalancer
```

the alb comes up with target groups for my graphite-ha and for the authenticate, but the health checks always fail with 404. 

i see in the logs for authenticate:
`{"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"10.200.2.244","path":"/","user-agent":"ELB-HealthChecker/2.0","referer":"","forwarded-for":"10.200.3.243","request-id":"c59f9ee4-7cc0-4eed-833f-e437e3891d86","duration":0.17436,"size":0,"response-code":404,"response-code-details":"route_not_found","time":"2021-06-29T00:39:56Z","message":"http-request"}
`

has anyone set this up behind an alb in a similar fashion with success?
