### ISSUE TITLE
Improved service mesh integration

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium-helm#235]
**Is your feature request related to a problem? Please describe.**

Presently, our `insecure` option changes a number of deployment time options, primarily optimized for running in a service mesh where all TLS is offloaded to the mesh.

However, as pointed out in https://github.com/pomerium/pomerium/issues/2387, our TCP tunneling does not work correctly if we don't terminate the HTTP connection ourselves.  More generally, users having to maintain service mesh configuration objects in _front_ of the pomerium proxy is additional configuration and performance overhead that is no longer necessary with the introduction of the ingress controller and our general pattern of being the user-facing edge proxy of any zero trust topology.

Concretely - our helm chart, as it is today, does not have all the right knobs to allow pomerium proxy to terminate inbound TLS/HTTP at edge, while offloading _internal_ communication to a secure service mesh.

**Describe the solution you'd like**

- Add configuration to enable/disable downstream TLS on the proxy service independently of the rest of the services
- Add per-deployment pod label customization settings
- Default proxy downstream TLS to enabled even in insecure mode
- Example istio deployment with new settings and labels as some istio specific labels are required

**Describe alternatives you've considered**

N/A

**Explain any additional use-cases**

Though the primary test case is istio, these settings should hopefully be useful in other service mesh deployments.

**Additional context**

n/a

**Comment by travisgroth** [comment]
Related - https://github.com/pomerium/pomerium-helm/pull/234

**Comment by anhdle14** [comment]
# Istio

For Istio ServiceMesh, one of the thing we can do is leverage the existing mTLS of Envoy pod via these tweaks to the pod itself.

```yaml
containers:
  - name: a-server
    ...
    volumeMounts:
      mountPath: /etc/certs/
      name: istio-certs
volumes:
  - emptyDir:
      medium: Memory
    name: istio-certs
```

And also with the annotations:

```yaml
spec:
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/includeInboundPorts: ""   # do not intercept any inbound ports
        traffic.sidecar.istio.io/includeOutboundIPRanges: ""  # do not intercept any outbound traffic
        proxy.istio.io/config: |  # configure an env variable `OUTPUT_CERTS` to write certificates to the given folder
          proxyMetadata:
            OUTPUT_CERTS: /etc/istio-output-certs
        sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]' # mount the shared volume at sidecar proxy
```

But currently there is no way to point via Helm values to a different location of the TLS. The only way to reference existing TLS from another secret.

This work around is documented on: https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings but the same can be done with Pomerium I guess.

Not sure about others but currently my deployment of Pomerium with Istio is like this: [values.yaml](https://github.com/anhdle14/thee/blob/main/deployment/pomerium/values.yaml).
