### ISSUE TITLE
Authenticate Endpoint is using internal cert rather than external

### ISSUE THREAD

**Issue by crdnl** [pomerium/pomerium-helm#247]
## What happened?

When deploying with the helm chart, and specifying ingress annotations, I expect to use the cert-manager for generating the external certificates.

For additional context, I'm attempting to follow the steps outlined here: https://cert-manager.io/docs/tutorials/acme/pomerium-ingress/

## What did you expect to happen?

When attempting to access `authenticate.sso.gg`, I receive an internal certificate signed by in `pomerium-tls`

## What's your environment like?

- Chart version: latest
- Container image: v0.16.0
- Kubernetes version: `v1.22.2+k3s2`
- Cloud provider: N/A
- Other details: 

## What are your chart values?

```yaml
authenticate:
  existingTLSSecret: pomerium-tls
  proxied: true
  idp:
    provider: "google"
    clientID: <snip>
    clientSecret: <snip>
    serviceAccount:
  ingress:
    annotations:
      cert-manager.io/issuer: cf-issuer-staging #DNS01 based ACME
    tls:
      secretName: auth.sso.gg-tls

proxy:
  existingTLSSecret: pomerium-tls

databroker:
  existingTLSSecret: pomerium-tls
  storage:
    clientTLS:
      existingSecretName: pomerium-redis-tls
      existingCASecretKey: ca.crt

authorize:
  existingTLSSecret: pomerium-tls

redis:
  enabled: true
  generateTLS: false
  tls:
    certificateSecret: pomerium-redis-tls

ingressController:
  enabled: true

config:
  rootDomain: sso.gg #Change this to your reserved domain space.
  existingCASecret: pomerium-tls
  generateTLS: false # On by default, disabled when cert-manager or another solution is in place.
```

## What are the contents of your config secret?

`kubectl get secret pomerium -o=jsonpath="{.data['config\.yaml']}" | base64 -D`

```values.yaml
autocert: false
dns_lookup_family: V4_ONLY
address: :443
grpc_address: :443
certificate_authority_file: "/pomerium/ca/ca.crt"
certificates:
http_redirect_addr: :80
authenticate_service_url: https://authenticate.sso.gg
authorize_service_url: https://pomerium-authorize.frontend.svc.cluster.local
databroker_service_url: https://pomerium-databroker.frontend.svc.cluster.local
idp_provider: google
idp_scopes:
idp_provider_url:
cookie_secret: #<snip>
shared_secret: #<snip>
idp_client_id: #<snip>
idp_client_secret: #<snip>
idp_service_account:
```

## Additional context

- I'm 99% sure this is a configuration issue on the Kubernetes side, but this is my first time interacting w/ Kubernetes.
