### ISSUE TITLE
404 page not found after upgrading from 30.0.2 to 30.1.0

### ISSUE THREAD

**Issue by beyondcloud-co** [pomerium/pomerium-helm#277]
Pomerium stopped working with `404` error after upgrading the helm chart from `30.0.2` to `30.1.0`. When downgrading back the helm chart everything is working fine.

Pomerium image itself is latest `0.17.0` which is working with the `30.0.2` chart version.

Here is the relevant part of the `values.yaml`.

```yaml
apiProxy:
  enabled: true
  ingress: true
  name: kubernetes
authenticate:
  name: "auth"
  proxied: true
  replicaCount: 2
config:
  insecure: true
  rootDomain: example.com
  existingSecret: pomerium-config
  existingSharedSecret: pomerium-shared
databroker:
  replicaCount: 2
extraEnv:
  IDP_SCOPES: openid,groups,profile,email,offline_access
  JWT_CLAIMS_HEADERS: email
forwardAuth:
  enabled: true
  internal: true
image:
  pullPolicy: IfNotPresent
  repository: pomerium/pomerium
  tag: v0.17.0
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-example-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  enabled: true
  hosts: []
  pathType: ImplementationSpecific
  secret:
    cert: ""
    key: ""
    name: pomerium-tls
  secretName: pomerium-ingress-tls
  tls:
    hosts: []
proxy:
  authenticateServiceUrl: https://auth.example.com
  authorizeInternalUrl: ""
  autoscaling:
    enabled: false
    minReplicas: 2
  replicaCount: 2
ingressController:
  enabled: false
```

It will be great to add some upgrade docs to fix this issue.

**Comment by travisgroth** [comment]
@beyondcloud-co I think this is a bug when using a third party ingress controller.  Should be an easy fix.

**Comment by beyondcloud-co** [comment]
@travisgroth the fix is working perfectly, thanks a lot!

**Comment by xbglowx** [comment]
I am having the same problem, but I am not using any Ingress, but just Solo's Gloo. Any recommendation? Worked just fine with 30.0.2.

**Comment by travisgroth** [comment]
> I am having the same problem, but I am not using any Ingress, but just Solo's Gloo. Any recommendation? Worked just fine with 30.0.2.

Please open a new issue with all the relevant configuration details.

**Comment by xbglowx** [comment]
> > I am having the same problem, but I am not using any Ingress, but just Solo's Gloo. Any recommendation? Worked just fine with 30.0.2.
> 
> Please open a new issue with all the relevant configuration details.

FYI, I believe https://github.com/pomerium/pomerium-helm/commit/948df542bdf0aefd3d7b20308da3d5d23e630804 fixed my problem

**Comment by pavankumar-go** [comment]
Using custom Ingress causing 404 error on authenticate service
```
"size":0,"response-code":404,"response-code-details":"route_not_found","time":"2022-10-13T06:58:16Z","message":"http-request"}
```

Ingress.yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custom-pomerium-ingress
  namespace: pomerium
spec:
  ingressClassName: nginx
  rules:
    - host: authenticate.dev.X.X
      http:
        paths:
          - backend:
              service:
                name: pomerium-authenticate
                port:
                  number: 80
            pathType: ImplementationSpecific
    - host: int-grafana.dev.X.X
      http:
        paths:
          - backend:
              service:
                name: pomerium-proxy
                port:
                  number: 80
            pathType: ImplementationSpecific
```

workaround: remove or set `AUTHENTICATE_INTERNAL_SERVICE_URL` to `https://authenticate.dev.X.X` from internal service dns url
