### ISSUE TITLE
no way to set proxy log level

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium-helm#297]
## What happened?
There appears to be no way to set the proxy log level. Neither of these worked:

```yaml
config:
  extraOpts:
    proxy_log_level: "debug"
proxy:
  deployment:
    extraEnv:
      PROXY_LOG_LEVEL: "debug"
```

## What did you expect to happen?
Envoy to start logging at the debug level.

## Steps to reproduce
1. Ran `x`
2. Clicked `y`
3. Saw error `z`

## What's your environment like?
- Chart version:
- Container image: 
- Kubernetes version:
- Cloud provider:
- Other details:

## What are your chart values?

```values.yaml
# Paste here
# Be sure to scrub any sensitive values
```

## What are the contents of your config secret?

`kubectl get secret pomerium -o=jsonpath="{.data['config\.yaml']}" | base64 -D`

```values.yaml
# Paste here
# Be sure to scrub any sensitive values
```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```
