### ISSUE TITLE
validation.yaml is blocking ingress creation when using operatorMode

### ISSUE THREAD

**Issue by hawkesn** [pomerium/pomerium-helm#330]
## What happened?

With the following variables set:
```
  ingressController:
    enabled: true
    config:
      operatorMode: true
```        

When attempting to render the helm chart, the following error occurs:
```
Error: Error: execution error at (pomerium/templates/validation.yaml:10:3): `ingressController.enabled` is not compatible with `ingress.enabled` unless legacy `ingressController.operatorMode`
```

## What did you expect to happen?
Successful render

## What's your environment like?

- Chart version: 32.0.6

## What are your chart values?

```values.yaml
  ingressController:
    enabled: true
    config:
      operatorMode: true
```

## Additional context

This is occurring because `validation.yaml` is referring to `ingressController.operatorMode` which was moved to `ingressController.config.operatorMode`

The work around is:

```
ingressController:
  enabled: true
  operatorMode: true
  ingressClassResource:
    enabled: false
  config:
    operatorMode: true
```
By putting `operatorMode` twice.
