### ISSUE TITLE
Using custom Ingress causing 404 error on authenticate service

### ISSUE THREAD

**Issue by pavankumar-go** [pomerium/pomerium-helm#333]
Using custom Ingress causing 404 error on authenticate service
```
"size":0,"response-code":404,"response-code-details":"route_not_found","time":"2022-10-13T06:58:16Z","message":"http-request"}
```

Ingress.yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custom-pomerium-ingress
  namespace: pomerium
spec:
  ingressClassName: nginx
  rules:
    - host: authenticate.dev.X.X
      http:
        paths:
          - backend:
              service:
                name: pomerium-authenticate
                port:
                  number: 80
            pathType: ImplementationSpecific
    - host: int-grafana.dev.X.X
      http:
        paths:
          - backend:
              service:
                name: pomerium-proxy
                port:
                  number: 80
            pathType: ImplementationSpecific
```

workaround: remove or set `AUTHENTICATE_INTERNAL_SERVICE_URL` to `https://authenticate.dev.X.X` 

```
  # we manage ingress on behalf of pomerium.
  # remove AUTHENTICATE_INTERNAL_SERVICE_URL from pomerium-authenticate.
  set {
    name  = "ingress.enabled"
    value = false
  }

  # workaround to fix 404 error in authenticate service
  set {
    name  = "extraEnv.AUTHENTICATE_INTERNAL_SERVICE_URL"
    value = "https://authenticate.dev.X.X"
  }
  ```

_Originally posted by @pavankumar-go in https://github.com/pomerium/pomerium-helm/issues/277#issuecomment-1277136087_
