### ISSUE TITLE
Chart doesn't support operator with existing config

### ISSUE THREAD

**Issue by abuzhynsky** [pomerium/pomerium-helm#71]
I'm trying to use the chart with the following configuration:

```yaml
config:
  existingConfig: "config"
operator:
  enabled: true
```

Seems that there are 2 problems:
1. existing config is mounted to the worker (authorize/proxy/etc.) pods instead of the new one generated by the operator
2. new empty config is not created during the chart installation
