### ISSUE TITLE
Simplify setting the basic auth header via values

### ISSUE THREAD

**Issue by abuzhynsky** [pomerium/pomerium-helm#78]
We're using the homegrown deployment system with very limited templating capabilities (basically it can only substitute the placeholders with the values from the secure storage during the Helm chart installation).
The username and password used in the basic auth for the proxied applications are stored separately and our deployment system doesn't support any dependencies between them. We can add new values with the `base64` representation but it's error-prone because we have a lot of `k8s` clusters with these applications.
The only option I've found is to use the `existingConfig`, use your chart as a subchart and generate the config with the `base64` representation in our chart but it potentially needs a lot of support in a long term perspective (we need to reflect all the changes made to the config).
Maybe it's possible to add a new optional section to the policy values in the chart like this which will be converted to the `set_request_headers` format?
```yaml
- from: https://app.example
  to: http://app.svc.cluster.local
  basicAuth:
    username: ""
    password: ""
```
I understand that it's a rather specific case but maybe it would be helpful for someone else.
I can submit a PR for this feature if you don't mind.

**Comment by travisgroth** [comment]
Hi @abuzhynsky,

If I'm understanding correctly, your secret injection must know specific helm values to substitute during installation?  eg, you tell it "set helm value `config.secureOption` to `X` from secret storage"? 

 We've recently changed the policy rendering a bit.  See https://github.com/pomerium/pomerium-helm/blob/903c0558273dd11d7691814c728385f4a8cad2c3/charts/pomerium/templates/_helpers.tpl#L446-L449.

Could you see if that does what you're looking for?  See https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function for usage.  I think you could then set arbitrary values at chart install time and reference them in your policy block by putting template syntax inside.

Sample Helm Values:
```yaml
myBasicAuthCreds: HTTPBASICAUTHCREDS
config:
  policy:
    - to: https://foo
       from: https://bar
       set_request_headers: "Authorization: Basic {{ .Values.myBasicAuthCreds }}"
```

Template rendered:
```yaml
    policy:
      - allowed_domains:
        - pomerium.com
        - gmail.com
        from: https://httpbin.localhost.pomerium.io
        pass_identity_headers: true
        set_request_headers: 'Authorization: Basic HTTPBASICAUTHCREDS'
        to: https://httpbin.org
```

**Comment by abuzhynsky** [comment]
Hello @travisgroth.

Thanks for your answer.

Not exactly. Our deployment system can substitute any placeholder in the values but is unable to make `base64` encoded string from the raw `username` and `password` values.

Anyway, the solution with the `tpl` function is great because we can do something like this:

```yaml
config:
  policy:
    - to: https://foo
      from: https://bar
      set_request_headers: 'Authorization: Basic {{(printf "%s:%s" .Values.username .Values.password)|b64enc}}'
```

where `username` and `password` are our substituted values.

Thanks for your help.
