### ISSUE TITLE
add JWT claim headers options

### ISSUE THREAD

**Issue by psychomelet** [pomerium/pomerium-helm#85]
related to https://github.com/pomerium/pomerium/pull/596

**Comment by travisgroth** [comment]
Specifying these options should be possible via the extraOpts parameter.  It was undocumented until recently.  See https://github.com/pomerium/pomerium-helm/pull/92

**Comment by psychomelet** [comment]
Not working as expected, I tried both extraOpts and extraEnv

```
# settings that are shared by all services
config:
  extraOpts:
    JWT_CLAIMS_HEADERS: email

extraEnv:
  JWT_CLAIMS_HEADERS: email
```
