### ISSUE TITLE
can't install chart with generateTLS "nil" in Secret.data.tls.crt

### ISSUE THREAD

**Issue by Vad1mo** [pomerium/pomerium-helm#87]
```yaml
#helm config
config.generateTLS: false
config.insecure: true
forwardAuth.enabled: true
```

[unknown object type "nil" in Secret.data.tls.crt, unknown object type "nil" in Secret.data.tls.key

```yaml
# Source: pomerium/templates/tls-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pomerium-tls
  labels:
    app.kubernetes.io/name: pomerium
    helm.sh/chart: pomerium-8.4.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: pomerium
type: kubernetes.io/tls
data:
  tls.crt: 
  tls.key:
```

I guess the error comes from not setting `generateTLS`

How could I do it if I want to set the Cert via Cert-manager if this is the cert for the public ingress.
